#Customize the codemagic.yml file according to your project and commit it to the root of the repository

workflows:
  happy-tracker-workflow:
    name: Happy Tracker Pipeline
    environment:
      xcode: latest
      vars:
          PROJECT: "happy-tracker.xcodeproj"
          SCHEME: "happy-tracker"
    #triggering:
      #events:
        #- push
      #branch_patterns:
        #- pattern: '*'
          #include: true
          #source: true
      #cancel_previous_builds: true
    scripts:
      - name: CICD Started
        script: echo "Welcome to happy tracker CI CD setup!"
      - name: iOS Run Test
        script: |
          xcode-project run-tests \
              --project "$PROJECT" \
              --scheme "$SCHEME" \
              --device "iPhone 11"
   #clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
        test_report: build/ios/test/*.xml
      - name: Build happy-tracker
        script: |
          xcodebuild build -project "$PROJECT" \
          -scheme "$SCHEME" \
          CODE_SIGN_INDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    publishing:
      email:
        recipients:
          - ajaxdwdev@gmail.com
